{% set name = "neptune" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6d9c7d9ea7344a2359c4ee47c50cc519121622b34e55e83eebd6bfd3638ddbd

build:
  noarch: python
  number: 0
  entry_points:
    - neptune = neptune.cli.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - bravado >=11.0.0,<12.0.0
    - click >=7.0
    - future >=0.17.1
    - gitpython >=2.0.8
    - oauthlib >=2.1.0
    - jsonschema-with-format
    - packaging
    - pandas
    - pillow >=1.1.6
    - psutil
    - pyjwt
    - python >=3.6
    - requests >=2.20.0
    - requests-oauthlib >=1.0.0
    - six >=1.12.0
    - urllib3
    - websocket-client >=0.35.0
    - boto3 >=1.28.0
    - swagger-spec-validator >=2.7.4

test:
  imports:
    - neptune
    - neptune.legacy
    - neptune.management
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client
  doc_url: https://docs.neptune.ai/
  dev_url: https://github.com/neptune-ai/neptune-client

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - Raalsky
    - PatrykGala
